import streamlit as st
st.title("Streamlit Docs")
st.write("This is a simple Streamlit app to demonstrate how to use Streamlit for building web applications.")

st.header("Getting Started")
st.subheader("Installation")
st.write("You can install Streamlit using pip:")
st.code("pip install streamlit")
st.subheader("Running the App")
st.write("To run the app, use the following command in your terminal:")
st.code("streamlit run main.py")
st.subheader("Creating Your First App")
st.write("Here's a simple example of a Streamlit app:")
st.code("import streamlit as st")
st.subheader("Title of the Website")
st.code("st.title('My First Streamlit App')")
st.title('My First Streamlit App')
st.subheader("Subheader")
st.code("st.subheader('This is a subheader')")
st.subheader('This is a subheader')
st.subheader("Text")
st.code("st.write('Hello, Streamlit!')")
st.write('Hello, Streamlit!')
st.subheader("List Selectbox")
st.code("option = st.selectbox('Select a number:', [1, 2,3,4,5])")